//              ,---------------------------,
//              |  /---------------------\  |
//              | |                       | |
//              | |     Jack Nemitz       | |
//              | |      CSCI 5611        | |
//              | |     Project 02        | |
//              | |     Node class        | |
//              |  \_____________________/  |
//              |___________________________|
//            ,---\_____     []     _______/------,
//          /         /______________\           /|
//        /___________________________________ /  | ___
//        |                                   |   |    )
//        |  _ _ _                 [-------]  |   |   (
//        |  o o o                 [-------]  |  /    _)_
//        |__________________________________ |/     /  /
//    /-------------------------------------/|      ( )/
//  /-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/ /
///-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/ /
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
//
// The code contained within this file and all supporting files is generated by me,
// from example code given in class (marked as such), or from documentation as appropriate.
//
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

public class Node {
  public PVector pos, vel, prev_pos;
  public float mass;
  public boolean[] torn = {false, false, false, false};

  public Node(PVector pos, PVector vel, float m) {
    this.pos = pos;
    this.prev_pos = pos;
    this.vel = vel;
    this.mass = m;
  }
}
